// Code generated by mcp-openapi-codegen. DO NOT EDIT.
package mcp

import (
	"context"
	"encoding/json"
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	target "github.com/yardrail/connectors/hubspot/crm-contacts/v3/client"
)

type ServiceResolver func(ctx context.Context) (*target.ClientWithResponses, error)

type Handler struct {
	resolve ServiceResolver
}

func NewHandler(resolve ServiceResolver) *Handler {
	return &Handler{resolve: resolve}
}

// RegisterBasic adds Basic tools to the given MCP server.
func (h *Handler) RegisterBasic(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("deletecrmv3objectscontacts-contact-id-archive",
			mcp.WithDescription("request returning *Deletecrmv3objectscontactsContactIdArchiveResponse"),
			mcp.WithString("contactId", mcp.Required(), mcp.Description("contactId")),
		),
		h.handleDeletecrmv3objectscontactsContactIdArchiveWithResponse,
	)

	s.AddTool(
		mcp.NewTool("getcrmv3objectscontacts-contact-id-get-by-id",
			mcp.WithDescription("request returning *Getcrmv3objectscontactsContactIdGetByIdResponse"),
			mcp.WithString("contactId", mcp.Required(), mcp.Description("contactId")),
			mcp.WithBoolean("archived", mcp.Description("Archived")),
			mcp.WithArray("associations", mcp.Description("Associations"), mcp.WithStringItems()),
			mcp.WithString("idProperty", mcp.Description("IdProperty")),
			mcp.WithArray("properties", mcp.Description("Properties"), mcp.WithStringItems()),
			mcp.WithArray("propertiesWithHistory", mcp.Description("PropertiesWithHistory"), mcp.WithStringItems()),
		),
		h.handleGetcrmv3objectscontactsContactIdGetByIdWithResponse,
	)

	s.AddTool(
		mcp.NewTool("getcrmv3objectscontacts-get-page",
			mcp.WithDescription("request returning *Getcrmv3objectscontactsGetPageResponse"),
			mcp.WithString("after", mcp.Description("After")),
			mcp.WithBoolean("archived", mcp.Description("Archived")),
			mcp.WithArray("associations", mcp.Description("Associations"), mcp.WithStringItems()),
			mcp.WithInteger("limit", mcp.Description("Limit")),
			mcp.WithArray("properties", mcp.Description("Properties"), mcp.WithStringItems()),
			mcp.WithArray("propertiesWithHistory", mcp.Description("PropertiesWithHistory"), mcp.WithStringItems()),
		),
		h.handleGetcrmv3objectscontactsGetPageWithResponse,
	)

	s.AddTool(
		mcp.NewTool("patchcrmv3objectscontacts-contact-id-update",
			mcp.WithDescription("Patchcrmv3objectscontactsContactIdUpdate"),
			mcp.WithString("contactId", mcp.Required(), mcp.Description("contactId")),
			mcp.WithString("idProperty", mcp.Description("IdProperty")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Patchcrmv3objectscontactsContactIdUpdateJSONRequestBody)")),
		),
		h.handlePatchcrmv3objectscontactsContactIdUpdateWithResponse,
	)

	s.AddTool(
		mcp.NewTool("postcrmv3objectscontacts-create",
			mcp.WithDescription("Postcrmv3objectscontactsCreate"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Postcrmv3objectscontactsCreateJSONRequestBody)")),
		),
		h.handlePostcrmv3objectscontactsCreateWithResponse,
	)

}

// RegisterBatch adds Batch tools to the given MCP server.
func (h *Handler) RegisterBatch(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("postcrmv3objectscontactsbatcharchive-archive",
			mcp.WithDescription("Postcrmv3objectscontactsbatcharchiveArchive"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Postcrmv3objectscontactsbatcharchiveArchiveJSONRequestBody)")),
		),
		h.handlePostcrmv3objectscontactsbatcharchiveArchiveWithResponse,
	)

	s.AddTool(
		mcp.NewTool("postcrmv3objectscontactsbatchcreate-create",
			mcp.WithDescription("Postcrmv3objectscontactsbatchcreateCreate"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Postcrmv3objectscontactsbatchcreateCreateJSONRequestBody)")),
		),
		h.handlePostcrmv3objectscontactsbatchcreateCreateWithResponse,
	)

	s.AddTool(
		mcp.NewTool("postcrmv3objectscontactsbatchread-read",
			mcp.WithDescription("Postcrmv3objectscontactsbatchreadRead"),
			mcp.WithBoolean("archived", mcp.Description("Archived")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Postcrmv3objectscontactsbatchreadReadJSONRequestBody)")),
		),
		h.handlePostcrmv3objectscontactsbatchreadReadWithResponse,
	)

	s.AddTool(
		mcp.NewTool("postcrmv3objectscontactsbatchupdate-update",
			mcp.WithDescription("Postcrmv3objectscontactsbatchupdateUpdate"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Postcrmv3objectscontactsbatchupdateUpdateJSONRequestBody)")),
		),
		h.handlePostcrmv3objectscontactsbatchupdateUpdateWithResponse,
	)

	s.AddTool(
		mcp.NewTool("postcrmv3objectscontactsbatchupsert-upsert",
			mcp.WithDescription("Postcrmv3objectscontactsbatchupsertUpsert"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Postcrmv3objectscontactsbatchupsertUpsertJSONRequestBody)")),
		),
		h.handlePostcrmv3objectscontactsbatchupsertUpsertWithResponse,
	)

}

// RegisterAdvanced adds Advanced tools to the given MCP server.
func (h *Handler) RegisterAdvanced(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("postcrmv3objectscontactsgdpr-delete-purge",
			mcp.WithDescription("Postcrmv3objectscontactsgdprDeletePurge"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Postcrmv3objectscontactsgdprDeletePurgeJSONRequestBody)")),
		),
		h.handlePostcrmv3objectscontactsgdprDeletePurgeWithResponse,
	)

	s.AddTool(
		mcp.NewTool("postcrmv3objectscontactsmerge-merge",
			mcp.WithDescription("Postcrmv3objectscontactsmergeMerge"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Postcrmv3objectscontactsmergeMergeJSONRequestBody)")),
		),
		h.handlePostcrmv3objectscontactsmergeMergeWithResponse,
	)

}

// RegisterSearch adds Search tools to the given MCP server.
func (h *Handler) RegisterSearch(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("postcrmv3objectscontactssearch-do-search",
			mcp.WithDescription("Postcrmv3objectscontactssearchDoSearch"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/hubspot/crm-contacts/v3/client.Postcrmv3objectscontactssearchDoSearchJSONRequestBody)")),
		),
		h.handlePostcrmv3objectscontactssearchDoSearchWithResponse,
	)

}

// RegisterAll adds all tools to the given MCP server.
func (h *Handler) RegisterAll(s *server.MCPServer) {
	h.RegisterBasic(s)
	h.RegisterBatch(s)
	h.RegisterAdvanced(s)
	h.RegisterSearch(s)
}

// Mounter can mount an MCPServer at a path. Implement this with your
// HTTP server's app type.
type Mounter interface {
	Mount(path string, s *server.MCPServer)
}

// MountAll creates one MCP server per tag group and mounts each at
// {prefix}/{tag-name}.
func (h *Handler) MountAll(m Mounter, prefix string) {
	{
		s := server.NewMCPServer("hubspot-crm-contacts-Basic", "0.1.0")
		h.RegisterBasic(s)
		m.Mount(prefix+"/basic", s)
	}
	{
		s := server.NewMCPServer("hubspot-crm-contacts-Batch", "0.1.0")
		h.RegisterBatch(s)
		m.Mount(prefix+"/batch", s)
	}
	{
		s := server.NewMCPServer("hubspot-crm-contacts-Advanced", "0.1.0")
		h.RegisterAdvanced(s)
		m.Mount(prefix+"/advanced", s)
	}
	{
		s := server.NewMCPServer("hubspot-crm-contacts-Search", "0.1.0")
		h.RegisterSearch(s)
		m.Mount(prefix+"/search", s)
	}
}
func ptrVal[T any](v T) *T {
	return &v
}

func getStringSlice(request mcp.CallToolRequest, key string) []string {
	args := request.GetArguments()
	if args == nil {
		return nil
	}
	v, ok := args[key]
	if !ok {
		return nil
	}
	slice, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(slice))
	for _, item := range slice {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func (h *Handler) handleDeletecrmv3objectscontactsContactIdArchiveWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	contactId := request.GetString("contactId", "")

	resp, err := client.Deletecrmv3objectscontactsContactIdArchiveWithResponse(ctx, contactId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetcrmv3objectscontactsContactIdGetByIdWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	contactId := request.GetString("contactId", "")
	params := &target.Getcrmv3objectscontactsContactIdGetByIdParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["archived"]; ok {
			params.Archived = ptrVal(request.GetBool("archived", false))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["associations"]; ok {
			params.Associations = ptrVal(getStringSlice(request, "associations"))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["idProperty"]; ok {
			params.IdProperty = ptrVal(request.GetString("idProperty", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["properties"]; ok {
			params.Properties = ptrVal(getStringSlice(request, "properties"))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["propertiesWithHistory"]; ok {
			params.PropertiesWithHistory = ptrVal(getStringSlice(request, "propertiesWithHistory"))
		}
	}

	resp, err := client.Getcrmv3objectscontactsContactIdGetByIdWithResponse(ctx, contactId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetcrmv3objectscontactsGetPageWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	params := &target.Getcrmv3objectscontactsGetPageParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["after"]; ok {
			params.After = ptrVal(request.GetString("after", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["archived"]; ok {
			params.Archived = ptrVal(request.GetBool("archived", false))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["associations"]; ok {
			params.Associations = ptrVal(getStringSlice(request, "associations"))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["limit"]; ok {
			params.Limit = ptrVal(int32(request.GetInt("limit", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["properties"]; ok {
			params.Properties = ptrVal(getStringSlice(request, "properties"))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["propertiesWithHistory"]; ok {
			params.PropertiesWithHistory = ptrVal(getStringSlice(request, "propertiesWithHistory"))
		}
	}

	resp, err := client.Getcrmv3objectscontactsGetPageWithResponse(ctx, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePatchcrmv3objectscontactsContactIdUpdateWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	contactId := request.GetString("contactId", "")
	var body target.Patchcrmv3objectscontactsContactIdUpdateJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}
	params := &target.Patchcrmv3objectscontactsContactIdUpdateParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["idProperty"]; ok {
			params.IdProperty = ptrVal(request.GetString("idProperty", ""))
		}
	}

	resp, err := client.Patchcrmv3objectscontactsContactIdUpdateWithResponse(ctx, contactId, params, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePostcrmv3objectscontactsCreateWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.Postcrmv3objectscontactsCreateJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.Postcrmv3objectscontactsCreateWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePostcrmv3objectscontactsbatcharchiveArchiveWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.Postcrmv3objectscontactsbatcharchiveArchiveJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.Postcrmv3objectscontactsbatcharchiveArchiveWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePostcrmv3objectscontactsbatchcreateCreateWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.Postcrmv3objectscontactsbatchcreateCreateJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.Postcrmv3objectscontactsbatchcreateCreateWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePostcrmv3objectscontactsbatchreadReadWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.Postcrmv3objectscontactsbatchreadReadJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}
	params := &target.Postcrmv3objectscontactsbatchreadReadParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["archived"]; ok {
			params.Archived = ptrVal(request.GetBool("archived", false))
		}
	}

	resp, err := client.Postcrmv3objectscontactsbatchreadReadWithResponse(ctx, params, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePostcrmv3objectscontactsbatchupdateUpdateWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.Postcrmv3objectscontactsbatchupdateUpdateJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.Postcrmv3objectscontactsbatchupdateUpdateWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePostcrmv3objectscontactsbatchupsertUpsertWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.Postcrmv3objectscontactsbatchupsertUpsertJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.Postcrmv3objectscontactsbatchupsertUpsertWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePostcrmv3objectscontactsgdprDeletePurgeWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.Postcrmv3objectscontactsgdprDeletePurgeJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.Postcrmv3objectscontactsgdprDeletePurgeWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePostcrmv3objectscontactsmergeMergeWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.Postcrmv3objectscontactsmergeMergeJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.Postcrmv3objectscontactsmergeMergeWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePostcrmv3objectscontactssearchDoSearchWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.Postcrmv3objectscontactssearchDoSearchJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.Postcrmv3objectscontactssearchDoSearchWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}
