// Code generated by mcp-openapi-codegen. DO NOT EDIT.
package mcp

import (
	"context"
	"encoding/json"
	"github.com/google/uuid"
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	target "github.com/yardrail/connectors/notion/notion/client"
)

type ServiceResolver func(ctx context.Context) (*target.ClientWithResponses, error)

type Handler struct {
	resolve ServiceResolver
}

func NewHandler(resolve ServiceResolver) *Handler {
	return &Handler{resolve: resolve}
}

// RegisterDataSources adds DataSources tools to the given MCP server.
func (h *Handler) RegisterDataSources(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-a-data-source",
			mcp.WithDescription("CreateADataSource"),
			mcp.WithString("Notion-Version", mcp.Description("NotionVersion")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/notion/notion/client.CreateADataSourceJSONRequestBody)")),
		),
		h.handleCreateADataSourceWithResponse,
	)

	s.AddTool(
		mcp.NewTool("list-data-source-templates",
			mcp.WithDescription("request returning *ListDataSourceTemplatesResponse"),
			mcp.WithString("dataSourceId", mcp.Required(), mcp.Description("dataSourceId")),
			mcp.WithString("start_cursor", mcp.Description("StartCursor")),
			mcp.WithInteger("page_size", mcp.Description("PageSize")),
			mcp.WithString("Notion-Version", mcp.Description("NotionVersion")),
		),
		h.handleListDataSourceTemplatesWithResponse,
	)

	s.AddTool(
		mcp.NewTool("query-data-source",
			mcp.WithDescription("QueryDataSource"),
			mcp.WithString("dataSourceId", mcp.Required(), mcp.Description("dataSourceId")),
			mcp.WithArray("filter_properties", mcp.Description("FilterProperties"), mcp.WithStringItems()),
			mcp.WithString("Notion-Version", mcp.Description("NotionVersion")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/notion/notion/client.QueryDataSourceJSONRequestBody)")),
		),
		h.handleQueryDataSourceWithResponse,
	)

	s.AddTool(
		mcp.NewTool("retrieve-a-data-source",
			mcp.WithDescription("request returning *RetrieveADataSourceResponse"),
			mcp.WithString("dataSourceId", mcp.Required(), mcp.Description("dataSourceId")),
			mcp.WithString("Notion-Version", mcp.Description("NotionVersion")),
		),
		h.handleRetrieveADataSourceWithResponse,
	)

	s.AddTool(
		mcp.NewTool("update-a-data-source",
			mcp.WithDescription("UpdateADataSource"),
			mcp.WithString("dataSourceId", mcp.Required(), mcp.Description("dataSourceId")),
			mcp.WithString("Notion-Version", mcp.Description("NotionVersion")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/notion/notion/client.UpdateADataSourceJSONRequestBody)")),
		),
		h.handleUpdateADataSourceWithResponse,
	)

}

// RegisterPages adds Pages tools to the given MCP server.
func (h *Handler) RegisterPages(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("move-page",
			mcp.WithDescription("MovePage"),
			mcp.WithString("pageId", mcp.Required(), mcp.Description("pageId")),
			mcp.WithString("Notion-Version", mcp.Description("NotionVersion")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/notion/notion/client.MovePageJSONRequestBody)")),
		),
		h.handleMovePageWithResponse,
	)

	s.AddTool(
		mcp.NewTool("retrieve-page-markdown",
			mcp.WithDescription("request returning *RetrievePageMarkdownResponse"),
			mcp.WithString("pageId", mcp.Required(), mcp.Description("pageId")),
			mcp.WithBoolean("include_transcript", mcp.Description("IncludeTranscript")),
			mcp.WithString("Notion-Version", mcp.Description("NotionVersion")),
		),
		h.handleRetrievePageMarkdownWithResponse,
	)

	s.AddTool(
		mcp.NewTool("update-page-markdown",
			mcp.WithDescription("UpdatePageMarkdown"),
			mcp.WithString("pageId", mcp.Required(), mcp.Description("pageId")),
			mcp.WithString("Notion-Version", mcp.Description("NotionVersion")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/notion/notion/client.UpdatePageMarkdownJSONRequestBody)")),
		),
		h.handleUpdatePageMarkdownWithResponse,
	)

}

// RegisterDatabases adds Databases tools to the given MCP server.
func (h *Handler) RegisterDatabases(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("retrieve-a-database",
			mcp.WithDescription("request returning *RetrieveADatabaseResponse"),
			mcp.WithString("databaseId", mcp.Required(), mcp.Description("databaseId")),
			mcp.WithString("Notion-Version", mcp.Description("NotionVersion")),
		),
		h.handleRetrieveADatabaseWithResponse,
	)

}

// RegisterAll adds all tools to the given MCP server.
func (h *Handler) RegisterAll(s *server.MCPServer) {
	h.RegisterDataSources(s)
	h.RegisterPages(s)
	h.RegisterDatabases(s)
}

// Mounter can mount an MCPServer at a path. Implement this with your
// HTTP server's app type.
type Mounter interface {
	Mount(path string, s *server.MCPServer)
}

// MountAll creates one MCP server per tag group and mounts each at
// {prefix}/{tag-name}.
func (h *Handler) MountAll(m Mounter, prefix string) {
	{
		s := server.NewMCPServer("notion-DataSources", "0.1.0")
		h.RegisterDataSources(s)
		m.Mount(prefix+"/data-sources", s)
	}
	{
		s := server.NewMCPServer("notion-Pages", "0.1.0")
		h.RegisterPages(s)
		m.Mount(prefix+"/pages", s)
	}
	{
		s := server.NewMCPServer("notion-Databases", "0.1.0")
		h.RegisterDatabases(s)
		m.Mount(prefix+"/databases", s)
	}
}
func ptrVal[T any](v T) *T {
	return &v
}

func parseUUID(s string) uuid.UUID {
	id, _ := uuid.Parse(s)
	return id
}

func getStringSlice(request mcp.CallToolRequest, key string) []string {
	args := request.GetArguments()
	if args == nil {
		return nil
	}
	v, ok := args[key]
	if !ok {
		return nil
	}
	slice, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(slice))
	for _, item := range slice {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func (h *Handler) handleCreateADataSourceWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateADataSourceJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}
	params := &target.CreateADataSourceParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["Notion-Version"]; ok {
			params.NotionVersion = ptrVal(target.NotionVersion(request.GetString("Notion-Version", "")))
		}
	}

	resp, err := client.CreateADataSourceWithResponse(ctx, params, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleListDataSourceTemplatesWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	dataSourceId := request.GetString("dataSourceId", "")
	params := &target.ListDataSourceTemplatesParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["start_cursor"]; ok {
			params.StartCursor = ptrVal(request.GetString("start_cursor", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["page_size"]; ok {
			params.PageSize = ptrVal(int(request.GetInt("page_size", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["Notion-Version"]; ok {
			params.NotionVersion = ptrVal(target.NotionVersion(request.GetString("Notion-Version", "")))
		}
	}

	resp, err := client.ListDataSourceTemplatesWithResponse(ctx, dataSourceId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleQueryDataSourceWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	dataSourceId := request.GetString("dataSourceId", "")
	var body target.QueryDataSourceJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}
	params := &target.QueryDataSourceParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["filter_properties"]; ok {
			params.FilterProperties = ptrVal(getStringSlice(request, "filter_properties"))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["Notion-Version"]; ok {
			params.NotionVersion = ptrVal(target.NotionVersion(request.GetString("Notion-Version", "")))
		}
	}

	resp, err := client.QueryDataSourceWithResponse(ctx, dataSourceId, params, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleRetrieveADataSourceWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	dataSourceId := request.GetString("dataSourceId", "")
	params := &target.RetrieveADataSourceParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["Notion-Version"]; ok {
			params.NotionVersion = ptrVal(target.NotionVersion(request.GetString("Notion-Version", "")))
		}
	}

	resp, err := client.RetrieveADataSourceWithResponse(ctx, dataSourceId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleUpdateADataSourceWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	dataSourceId := request.GetString("dataSourceId", "")
	var body target.UpdateADataSourceJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}
	params := &target.UpdateADataSourceParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["Notion-Version"]; ok {
			params.NotionVersion = ptrVal(target.NotionVersion(request.GetString("Notion-Version", "")))
		}
	}

	resp, err := client.UpdateADataSourceWithResponse(ctx, dataSourceId, params, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleMovePageWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	pageId := request.GetString("pageId", "")
	var body target.MovePageJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}
	params := &target.MovePageParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["Notion-Version"]; ok {
			params.NotionVersion = ptrVal(target.NotionVersion(request.GetString("Notion-Version", "")))
		}
	}

	resp, err := client.MovePageWithResponse(ctx, parseUUID(pageId), params, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleRetrievePageMarkdownWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	pageId := request.GetString("pageId", "")
	params := &target.RetrievePageMarkdownParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["include_transcript"]; ok {
			params.IncludeTranscript = ptrVal(request.GetBool("include_transcript", false))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["Notion-Version"]; ok {
			params.NotionVersion = request.GetString("Notion-Version", "")
		}
	}

	resp, err := client.RetrievePageMarkdownWithResponse(ctx, parseUUID(pageId), params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleUpdatePageMarkdownWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	pageId := request.GetString("pageId", "")
	var body target.UpdatePageMarkdownJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}
	params := &target.UpdatePageMarkdownParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["Notion-Version"]; ok {
			params.NotionVersion = request.GetString("Notion-Version", "")
		}
	}

	resp, err := client.UpdatePageMarkdownWithResponse(ctx, parseUUID(pageId), params, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleRetrieveADatabaseWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	databaseId := request.GetString("databaseId", "")
	params := &target.RetrieveADatabaseParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["Notion-Version"]; ok {
			params.NotionVersion = ptrVal(target.NotionVersion(request.GetString("Notion-Version", "")))
		}
	}

	resp, err := client.RetrieveADatabaseWithResponse(ctx, databaseId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}
