// Code generated by mcp-openapi-codegen. DO NOT EDIT.
package mcp

import (
	"context"
	"encoding/json"
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	target "github.com/yardrail/connectors/canva/canva/client"
)

type ServiceResolver func(ctx context.Context) (*target.ClientWithResponses, error)

type Handler struct {
	resolve ServiceResolver
}

func NewHandler(resolve ServiceResolver) *Handler {
	return &Handler{resolve: resolve}
}

// RegisterComment adds Comment tools to the given MCP server.
func (h *Handler) RegisterComment(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-comment",
			mcp.WithDescription("CreateComment"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateCommentJSONRequestBody)")),
		),
		h.handleCreateCommentWithResponse,
	)

	s.AddTool(
		mcp.NewTool("create-reply",
			mcp.WithDescription("CreateReply"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithString("threadId", mcp.Required(), mcp.Description("threadId")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateReplyJSONRequestBody)")),
		),
		h.handleCreateReplyWithResponse,
	)

	s.AddTool(
		mcp.NewTool("create-thread",
			mcp.WithDescription("CreateThread"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateThreadJSONRequestBody)")),
		),
		h.handleCreateThreadWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-reply",
			mcp.WithDescription("request returning *GetReplyResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithString("threadId", mcp.Required(), mcp.Description("threadId")),
			mcp.WithString("replyId", mcp.Required(), mcp.Description("replyId")),
		),
		h.handleGetReplyWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-thread",
			mcp.WithDescription("request returning *GetThreadResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithString("threadId", mcp.Required(), mcp.Description("threadId")),
		),
		h.handleGetThreadWithResponse,
	)

	s.AddTool(
		mcp.NewTool("list-replies",
			mcp.WithDescription("request returning *ListRepliesResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithString("threadId", mcp.Required(), mcp.Description("threadId")),
			mcp.WithInteger("limit", mcp.Description("Limit")),
			mcp.WithString("continuation", mcp.Description("Continuation")),
		),
		h.handleListRepliesWithResponse,
	)

}

// RegisterAutofill adds Autofill tools to the given MCP server.
func (h *Handler) RegisterAutofill(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-design-autofill-job",
			mcp.WithDescription("CreateDesignAutofillJob"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateDesignAutofillJobJSONRequestBody)")),
		),
		h.handleCreateDesignAutofillJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-autofill-job",
			mcp.WithDescription("request returning *GetDesignAutofillJobResp"),
			mcp.WithString("jobId", mcp.Required(), mcp.Description("jobId")),
		),
		h.handleGetDesignAutofillJobWithResponse,
	)

}

// RegisterExport adds Export tools to the given MCP server.
func (h *Handler) RegisterExport(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-design-export-job",
			mcp.WithDescription("CreateDesignExportJob"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateDesignExportJobJSONRequestBody)")),
		),
		h.handleCreateDesignExportJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("create-print-partner-design-export-job",
			mcp.WithDescription("CreatePrintPartnerDesignExportJob"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreatePrintPartnerDesignExportJobJSONRequestBody)")),
		),
		h.handleCreatePrintPartnerDesignExportJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-export-job",
			mcp.WithDescription("request returning *GetDesignExportJobResp"),
			mcp.WithString("exportId", mcp.Required(), mcp.Description("exportId")),
		),
		h.handleGetDesignExportJobWithResponse,
	)

}

// RegisterMerge adds Merge tools to the given MCP server.
func (h *Handler) RegisterMerge(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-design-merge-job",
			mcp.WithDescription("CreateDesignMergeJob"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateDesignMergeJobJSONRequestBody)")),
		),
		h.handleCreateDesignMergeJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-merge-job",
			mcp.WithDescription("request returning *GetDesignMergeJobResp"),
			mcp.WithString("jobId", mcp.Required(), mcp.Description("jobId")),
		),
		h.handleGetDesignMergeJobWithResponse,
	)

}

// RegisterResize adds Resize tools to the given MCP server.
func (h *Handler) RegisterResize(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-design-resize-job",
			mcp.WithDescription("CreateDesignResizeJob"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateDesignResizeJobJSONRequestBody)")),
		),
		h.handleCreateDesignResizeJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-resize-job",
			mcp.WithDescription("request returning *GetDesignResizeJobResp"),
			mcp.WithString("jobId", mcp.Required(), mcp.Description("jobId")),
		),
		h.handleGetDesignResizeJobWithResponse,
	)

}

// RegisterDesign adds Design tools to the given MCP server.
func (h *Handler) RegisterDesign(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-design",
			mcp.WithDescription("CreateDesign"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateDesignJSONRequestBody)")),
		),
		h.handleCreateDesignWithResponse,
	)

	s.AddTool(
		mcp.NewTool("create-print-partner-design",
			mcp.WithDescription("CreatePrintPartnerDesign"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreatePrintPartnerDesignJSONRequestBody)")),
		),
		h.handleCreatePrintPartnerDesignWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-dataset",
			mcp.WithDescription("request returning *GetDesignDatasetResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
		),
		h.handleGetDesignDatasetWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-export-formats",
			mcp.WithDescription("request returning *GetDesignExportFormatsResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
		),
		h.handleGetDesignExportFormatsWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-pages",
			mcp.WithDescription("request returning *GetDesignPagesResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithInteger("offset", mcp.Description("Offset")),
			mcp.WithInteger("limit", mcp.Description("Limit")),
		),
		h.handleGetDesignPagesWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design",
			mcp.WithDescription("request returning *GetDesignResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
		),
		h.handleGetDesignWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-print-partner-design",
			mcp.WithDescription("request returning *GetPrintPartnerDesignResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithInteger("bleed", mcp.Description("Bleed")),
			mcp.WithInteger("min_pages", mcp.Description("MinPages")),
			mcp.WithInteger("max_pages", mcp.Description("MaxPages")),
		),
		h.handleGetPrintPartnerDesignWithResponse,
	)

	s.AddTool(
		mcp.NewTool("list-designs",
			mcp.WithDescription("request returning *ListDesignsResp"),
			mcp.WithString("query", mcp.Description("Query")),
			mcp.WithString("continuation", mcp.Description("Continuation")),
			mcp.WithString("ownership", mcp.Description("Ownership")),
			mcp.WithString("sort_by", mcp.Description("SortBy")),
			mcp.WithInteger("limit", mcp.Description("Limit")),
		),
		h.handleListDesignsWithResponse,
	)

}

// RegisterFolder adds Folder tools to the given MCP server.
func (h *Handler) RegisterFolder(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-folder",
			mcp.WithDescription("CreateFolder"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateFolderJSONRequestBody)")),
		),
		h.handleCreateFolderWithResponse,
	)

	s.AddTool(
		mcp.NewTool("delete-folder",
			mcp.WithDescription("request returning *DeleteFolderResp"),
			mcp.WithString("folderId", mcp.Required(), mcp.Description("folderId")),
		),
		h.handleDeleteFolderWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-folder",
			mcp.WithDescription("request returning *GetFolderResp"),
			mcp.WithString("folderId", mcp.Required(), mcp.Description("folderId")),
		),
		h.handleGetFolderWithResponse,
	)

	s.AddTool(
		mcp.NewTool("list-folder-items",
			mcp.WithDescription("request returning *ListFolderItemsResp"),
			mcp.WithString("folderId", mcp.Required(), mcp.Description("folderId")),
			mcp.WithString("continuation", mcp.Description("Continuation")),
			mcp.WithInteger("limit", mcp.Description("Limit")),
			mcp.WithString("sort_by", mcp.Description("SortBy")),
			mcp.WithString("pin_status", mcp.Description("PinStatus")),
		),
		h.handleListFolderItemsWithResponse,
	)

	s.AddTool(
		mcp.NewTool("move-folder-item",
			mcp.WithDescription("MoveFolderItem"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.MoveFolderItemJSONRequestBody)")),
		),
		h.handleMoveFolderItemWithResponse,
	)

	s.AddTool(
		mcp.NewTool("update-folder",
			mcp.WithDescription("UpdateFolder"),
			mcp.WithString("folderId", mcp.Required(), mcp.Description("folderId")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.UpdateFolderJSONRequestBody)")),
		),
		h.handleUpdateFolderWithResponse,
	)

}

// RegisterDesignImport adds DesignImport tools to the given MCP server.
func (h *Handler) RegisterDesignImport(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-image-to-design-import-job",
			mcp.WithDescription("CreateImageToDesignImportJob"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateImageToDesignImportJobJSONRequestBody)")),
		),
		h.handleCreateImageToDesignImportJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("create-url-import-job",
			mcp.WithDescription("CreateUrlImportJob"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateUrlImportJobJSONRequestBody)")),
		),
		h.handleCreateUrlImportJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-import-job",
			mcp.WithDescription("request returning *GetDesignImportJobResp"),
			mcp.WithString("jobId", mcp.Required(), mcp.Description("jobId")),
		),
		h.handleGetDesignImportJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-image-to-design-import-job",
			mcp.WithDescription("request returning *GetImageToDesignImportJobResp"),
			mcp.WithString("jobId", mcp.Required(), mcp.Description("jobId")),
		),
		h.handleGetImageToDesignImportJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-url-import-job",
			mcp.WithDescription("request returning *GetUrlImportJobResp"),
			mcp.WithString("jobId", mcp.Required(), mcp.Description("jobId")),
		),
		h.handleGetUrlImportJobWithResponse,
	)

}

// RegisterImageTransformation adds ImageTransformation tools to the given MCP server.
func (h *Handler) RegisterImageTransformation(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-image-transformation-job",
			mcp.WithDescription("CreateImageTransformationJob"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateImageTransformationJobJSONRequestBody)")),
		),
		h.handleCreateImageTransformationJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-image-transformation-job",
			mcp.WithDescription("request returning *GetImageTransformationJobResp"),
			mcp.WithString("jobId", mcp.Required(), mcp.Description("jobId")),
		),
		h.handleGetImageTransformationJobWithResponse,
	)

}

// RegisterAsset adds Asset tools to the given MCP server.
func (h *Handler) RegisterAsset(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("create-url-asset-upload-job",
			mcp.WithDescription("CreateUrlAssetUploadJob"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.CreateUrlAssetUploadJobJSONRequestBody)")),
		),
		h.handleCreateUrlAssetUploadJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("delete-asset",
			mcp.WithDescription("request returning *DeleteAssetResp"),
			mcp.WithString("assetId", mcp.Required(), mcp.Description("assetId")),
		),
		h.handleDeleteAssetWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-asset-upload-job",
			mcp.WithDescription("request returning *GetAssetUploadJobResp"),
			mcp.WithString("jobId", mcp.Required(), mcp.Description("jobId")),
		),
		h.handleGetAssetUploadJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-asset",
			mcp.WithDescription("request returning *GetAssetResp"),
			mcp.WithString("assetId", mcp.Required(), mcp.Description("assetId")),
		),
		h.handleGetAssetWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-url-asset-upload-job",
			mcp.WithDescription("request returning *GetUrlAssetUploadJobResp"),
			mcp.WithString("jobId", mcp.Required(), mcp.Description("jobId")),
		),
		h.handleGetUrlAssetUploadJobWithResponse,
	)

	s.AddTool(
		mcp.NewTool("update-asset",
			mcp.WithDescription("UpdateAsset"),
			mcp.WithString("assetId", mcp.Required(), mcp.Description("assetId")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.UpdateAssetJSONRequestBody)")),
		),
		h.handleUpdateAssetWithResponse,
	)

}

// RegisterOauth adds Oauth tools to the given MCP server.
func (h *Handler) RegisterOauth(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("exchange-access-token-with-formdata-body",
			mcp.WithDescription("ExchangeAccessTokenWithFormdataBody"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.ExchangeAccessTokenFormdataRequestBody)")),
		),
		h.handleExchangeAccessTokenWithFormdataBodyWithResponse,
	)

	s.AddTool(
		mcp.NewTool("introspect-token-with-formdata-body",
			mcp.WithDescription("IntrospectTokenWithFormdataBody"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.IntrospectTokenFormdataRequestBody)")),
		),
		h.handleIntrospectTokenWithFormdataBodyWithResponse,
	)

	s.AddTool(
		mcp.NewTool("revoke-tokens-with-formdata-body",
			mcp.WithDescription("RevokeTokensWithFormdataBody"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.RevokeTokensFormdataRequestBody)")),
		),
		h.handleRevokeTokensWithFormdataBodyWithResponse,
	)

}

// RegisterApp adds App tools to the given MCP server.
func (h *Handler) RegisterApp(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("get-app-jwks",
			mcp.WithDescription("request returning *GetAppJwksResp"),
			mcp.WithString("appId", mcp.Required(), mcp.Description("appId")),
		),
		h.handleGetAppJwksWithResponse,
	)

}

// RegisterBrandTemplate adds BrandTemplate tools to the given MCP server.
func (h *Handler) RegisterBrandTemplate(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("get-brand-template-dataset",
			mcp.WithDescription("request returning *GetBrandTemplateDatasetResp"),
			mcp.WithString("brandTemplateId", mcp.Required(), mcp.Description("brandTemplateId")),
		),
		h.handleGetBrandTemplateDatasetWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-brand-template",
			mcp.WithDescription("request returning *GetBrandTemplateResp"),
			mcp.WithString("brandTemplateId", mcp.Required(), mcp.Description("brandTemplateId")),
		),
		h.handleGetBrandTemplateWithResponse,
	)

	s.AddTool(
		mcp.NewTool("list-brand-templates",
			mcp.WithDescription("request returning *ListBrandTemplatesResp"),
			mcp.WithString("query", mcp.Description("Query")),
			mcp.WithString("continuation", mcp.Description("Continuation")),
			mcp.WithInteger("limit", mcp.Description("Limit")),
			mcp.WithString("ownership", mcp.Description("Ownership")),
			mcp.WithString("sort_by", mcp.Description("SortBy")),
			mcp.WithString("dataset", mcp.Description("Dataset")),
		),
		h.handleListBrandTemplatesWithResponse,
	)

	s.AddTool(
		mcp.NewTool("publish-brand-template",
			mcp.WithDescription("PublishBrandTemplate"),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.PublishBrandTemplateJSONRequestBody)")),
		),
		h.handlePublishBrandTemplateWithResponse,
	)

}

// RegisterAnalytics adds Analytics tools to the given MCP server.
func (h *Handler) RegisterAnalytics(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("get-design-analytics-links",
			mcp.WithDescription("request returning *GetDesignAnalyticsLinksResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithInteger("limit", mcp.Description("Limit")),
			mcp.WithString("continuation", mcp.Description("Continuation")),
		),
		h.handleGetDesignAnalyticsLinksWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-analytics-page-views",
			mcp.WithDescription("GetDesignAnalyticsPageViews"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithObject("body", mcp.Required(), mcp.Description("Request body (github.com/yardrail/connectors/canva/canva/client.GetDesignAnalyticsPageViewsJSONRequestBody)")),
		),
		h.handleGetDesignAnalyticsPageViewsWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-analytics-viewers",
			mcp.WithDescription("request returning *GetDesignAnalyticsViewersResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithString("link_id", mcp.Description("LinkId")),
			mcp.WithInteger("first_viewed_after", mcp.Description("FirstViewedAfter")),
			mcp.WithInteger("limit", mcp.Description("Limit")),
			mcp.WithString("continuation", mcp.Description("Continuation")),
		),
		h.handleGetDesignAnalyticsViewersWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-analytics-views-over-time",
			mcp.WithDescription("request returning *GetDesignAnalyticsViewsOverTimeResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
			mcp.WithInteger("start_time", mcp.Description("StartTime")),
			mcp.WithInteger("end_time", mcp.Description("EndTime")),
			mcp.WithString("timezone", mcp.Description("Timezone")),
			mcp.WithInteger("limit", mcp.Description("Limit")),
			mcp.WithString("continuation", mcp.Description("Continuation")),
		),
		h.handleGetDesignAnalyticsViewsOverTimeWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-design-analytics",
			mcp.WithDescription("request returning *GetDesignAnalyticsResp"),
			mcp.WithString("designId", mcp.Required(), mcp.Description("designId")),
		),
		h.handleGetDesignAnalyticsWithResponse,
	)

}

// RegisterOidc adds Oidc tools to the given MCP server.
func (h *Handler) RegisterOidc(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("get-oidc-jwks",
			mcp.WithDescription("request returning *GetOidcJwksResp"),
		),
		h.handleGetOidcJwksWithResponse,
	)

	s.AddTool(
		mcp.NewTool("user-info",
			mcp.WithDescription("request returning *UserInfoResp"),
		),
		h.handleUserInfoWithResponse,
	)

}

// RegisterConnect adds Connect tools to the given MCP server.
func (h *Handler) RegisterConnect(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("get-signing-public-keys",
			mcp.WithDescription("request returning *GetSigningPublicKeysResp"),
		),
		h.handleGetSigningPublicKeysWithResponse,
	)

}

// RegisterUser adds User tools to the given MCP server.
func (h *Handler) RegisterUser(s *server.MCPServer) {

	s.AddTool(
		mcp.NewTool("get-user-capabilities",
			mcp.WithDescription("request returning *GetUserCapabilitiesResp"),
		),
		h.handleGetUserCapabilitiesWithResponse,
	)

	s.AddTool(
		mcp.NewTool("get-user-profile",
			mcp.WithDescription("request returning *GetUserProfileResp"),
		),
		h.handleGetUserProfileWithResponse,
	)

	s.AddTool(
		mcp.NewTool("users-me",
			mcp.WithDescription("request returning *UsersMeResp"),
		),
		h.handleUsersMeWithResponse,
	)

}

// RegisterAll adds all tools to the given MCP server.
func (h *Handler) RegisterAll(s *server.MCPServer) {
	h.RegisterComment(s)
	h.RegisterAutofill(s)
	h.RegisterExport(s)
	h.RegisterMerge(s)
	h.RegisterResize(s)
	h.RegisterDesign(s)
	h.RegisterFolder(s)
	h.RegisterDesignImport(s)
	h.RegisterImageTransformation(s)
	h.RegisterAsset(s)
	h.RegisterOauth(s)
	h.RegisterApp(s)
	h.RegisterBrandTemplate(s)
	h.RegisterAnalytics(s)
	h.RegisterOidc(s)
	h.RegisterConnect(s)
	h.RegisterUser(s)
}

// Mounter can mount an MCPServer at a path. Implement this with your
// HTTP server's app type.
type Mounter interface {
	Mount(path string, s *server.MCPServer)
}

// MountAll creates one MCP server per tag group and mounts each at
// {prefix}/{tag-name}.
func (h *Handler) MountAll(m Mounter, prefix string) {
	{
		s := server.NewMCPServer("canva-Comment", "0.1.0")
		h.RegisterComment(s)
		m.Mount(prefix+"/comment", s)
	}
	{
		s := server.NewMCPServer("canva-Autofill", "0.1.0")
		h.RegisterAutofill(s)
		m.Mount(prefix+"/autofill", s)
	}
	{
		s := server.NewMCPServer("canva-Export", "0.1.0")
		h.RegisterExport(s)
		m.Mount(prefix+"/export", s)
	}
	{
		s := server.NewMCPServer("canva-Merge", "0.1.0")
		h.RegisterMerge(s)
		m.Mount(prefix+"/merge", s)
	}
	{
		s := server.NewMCPServer("canva-Resize", "0.1.0")
		h.RegisterResize(s)
		m.Mount(prefix+"/resize", s)
	}
	{
		s := server.NewMCPServer("canva-Design", "0.1.0")
		h.RegisterDesign(s)
		m.Mount(prefix+"/design", s)
	}
	{
		s := server.NewMCPServer("canva-Folder", "0.1.0")
		h.RegisterFolder(s)
		m.Mount(prefix+"/folder", s)
	}
	{
		s := server.NewMCPServer("canva-DesignImport", "0.1.0")
		h.RegisterDesignImport(s)
		m.Mount(prefix+"/design-import", s)
	}
	{
		s := server.NewMCPServer("canva-ImageTransformation", "0.1.0")
		h.RegisterImageTransformation(s)
		m.Mount(prefix+"/image-transformation", s)
	}
	{
		s := server.NewMCPServer("canva-Asset", "0.1.0")
		h.RegisterAsset(s)
		m.Mount(prefix+"/asset", s)
	}
	{
		s := server.NewMCPServer("canva-Oauth", "0.1.0")
		h.RegisterOauth(s)
		m.Mount(prefix+"/oauth", s)
	}
	{
		s := server.NewMCPServer("canva-App", "0.1.0")
		h.RegisterApp(s)
		m.Mount(prefix+"/app", s)
	}
	{
		s := server.NewMCPServer("canva-BrandTemplate", "0.1.0")
		h.RegisterBrandTemplate(s)
		m.Mount(prefix+"/brand-template", s)
	}
	{
		s := server.NewMCPServer("canva-Analytics", "0.1.0")
		h.RegisterAnalytics(s)
		m.Mount(prefix+"/analytics", s)
	}
	{
		s := server.NewMCPServer("canva-Oidc", "0.1.0")
		h.RegisterOidc(s)
		m.Mount(prefix+"/oidc", s)
	}
	{
		s := server.NewMCPServer("canva-Connect", "0.1.0")
		h.RegisterConnect(s)
		m.Mount(prefix+"/connect", s)
	}
	{
		s := server.NewMCPServer("canva-User", "0.1.0")
		h.RegisterUser(s)
		m.Mount(prefix+"/user", s)
	}
}
func ptrVal[T any](v T) *T {
	return &v
}

func (h *Handler) handleCreateCommentWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateCommentJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateCommentWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateReplyWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	threadId := request.GetString("threadId", "")
	var body target.CreateReplyJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateReplyWithResponse(ctx, designId, threadId, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateThreadWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	var body target.CreateThreadJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateThreadWithResponse(ctx, designId, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetReplyWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	threadId := request.GetString("threadId", "")
	replyId := request.GetString("replyId", "")

	resp, err := client.GetReplyWithResponse(ctx, designId, threadId, replyId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetThreadWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	threadId := request.GetString("threadId", "")

	resp, err := client.GetThreadWithResponse(ctx, designId, threadId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleListRepliesWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	threadId := request.GetString("threadId", "")
	params := &target.ListRepliesParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["limit"]; ok {
			params.Limit = ptrVal(int32(request.GetInt("limit", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["continuation"]; ok {
			params.Continuation = ptrVal(request.GetString("continuation", ""))
		}
	}

	resp, err := client.ListRepliesWithResponse(ctx, designId, threadId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateDesignAutofillJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateDesignAutofillJobJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateDesignAutofillJobWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignAutofillJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	jobId := request.GetString("jobId", "")

	resp, err := client.GetDesignAutofillJobWithResponse(ctx, jobId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateDesignExportJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateDesignExportJobJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateDesignExportJobWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreatePrintPartnerDesignExportJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreatePrintPartnerDesignExportJobJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreatePrintPartnerDesignExportJobWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignExportJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	exportId := request.GetString("exportId", "")

	resp, err := client.GetDesignExportJobWithResponse(ctx, exportId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateDesignMergeJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateDesignMergeJobJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateDesignMergeJobWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignMergeJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	jobId := request.GetString("jobId", "")

	resp, err := client.GetDesignMergeJobWithResponse(ctx, jobId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateDesignResizeJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateDesignResizeJobJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateDesignResizeJobWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignResizeJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	jobId := request.GetString("jobId", "")

	resp, err := client.GetDesignResizeJobWithResponse(ctx, jobId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateDesignWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateDesignJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateDesignWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreatePrintPartnerDesignWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreatePrintPartnerDesignJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreatePrintPartnerDesignWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignDatasetWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")

	resp, err := client.GetDesignDatasetWithResponse(ctx, designId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignExportFormatsWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")

	resp, err := client.GetDesignExportFormatsWithResponse(ctx, designId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignPagesWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	params := &target.GetDesignPagesParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["offset"]; ok {
			params.Offset = ptrVal(int32(request.GetInt("offset", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["limit"]; ok {
			params.Limit = ptrVal(int32(request.GetInt("limit", 0)))
		}
	}

	resp, err := client.GetDesignPagesWithResponse(ctx, designId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")

	resp, err := client.GetDesignWithResponse(ctx, designId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetPrintPartnerDesignWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	params := &target.GetPrintPartnerDesignParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["bleed"]; ok {
			params.Bleed = ptrVal(int32(request.GetInt("bleed", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["min_pages"]; ok {
			params.MinPages = ptrVal(int32(request.GetInt("min_pages", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["max_pages"]; ok {
			params.MaxPages = ptrVal(int32(request.GetInt("max_pages", 0)))
		}
	}

	resp, err := client.GetPrintPartnerDesignWithResponse(ctx, designId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleListDesignsWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	params := &target.ListDesignsParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["query"]; ok {
			params.Query = ptrVal(request.GetString("query", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["continuation"]; ok {
			params.Continuation = ptrVal(request.GetString("continuation", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["ownership"]; ok {
			params.Ownership = ptrVal(target.OwnershipType(request.GetString("ownership", "")))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["sort_by"]; ok {
			params.SortBy = ptrVal(target.SortByType(request.GetString("sort_by", "")))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["limit"]; ok {
			params.Limit = ptrVal(int32(request.GetInt("limit", 0)))
		}
	}

	resp, err := client.ListDesignsWithResponse(ctx, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateFolderWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateFolderJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateFolderWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleDeleteFolderWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	folderId := request.GetString("folderId", "")

	resp, err := client.DeleteFolderWithResponse(ctx, folderId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetFolderWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	folderId := request.GetString("folderId", "")

	resp, err := client.GetFolderWithResponse(ctx, folderId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleListFolderItemsWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	folderId := request.GetString("folderId", "")
	params := &target.ListFolderItemsParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["continuation"]; ok {
			params.Continuation = ptrVal(request.GetString("continuation", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["limit"]; ok {
			params.Limit = ptrVal(int32(request.GetInt("limit", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["sort_by"]; ok {
			params.SortBy = ptrVal(target.FolderItemSortBy(request.GetString("sort_by", "")))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["pin_status"]; ok {
			params.PinStatus = ptrVal(target.FolderItemPinStatus(request.GetString("pin_status", "")))
		}
	}

	resp, err := client.ListFolderItemsWithResponse(ctx, folderId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleMoveFolderItemWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.MoveFolderItemJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.MoveFolderItemWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleUpdateFolderWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	folderId := request.GetString("folderId", "")
	var body target.UpdateFolderJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.UpdateFolderWithResponse(ctx, folderId, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateImageToDesignImportJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateImageToDesignImportJobJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateImageToDesignImportJobWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateUrlImportJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateUrlImportJobJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateUrlImportJobWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignImportJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	jobId := request.GetString("jobId", "")

	resp, err := client.GetDesignImportJobWithResponse(ctx, jobId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetImageToDesignImportJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	jobId := request.GetString("jobId", "")

	resp, err := client.GetImageToDesignImportJobWithResponse(ctx, jobId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetUrlImportJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	jobId := request.GetString("jobId", "")

	resp, err := client.GetUrlImportJobWithResponse(ctx, jobId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateImageTransformationJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateImageTransformationJobJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateImageTransformationJobWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetImageTransformationJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	jobId := request.GetString("jobId", "")

	resp, err := client.GetImageTransformationJobWithResponse(ctx, jobId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleCreateUrlAssetUploadJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.CreateUrlAssetUploadJobJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.CreateUrlAssetUploadJobWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleDeleteAssetWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	assetId := request.GetString("assetId", "")

	resp, err := client.DeleteAssetWithResponse(ctx, assetId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetAssetUploadJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	jobId := request.GetString("jobId", "")

	resp, err := client.GetAssetUploadJobWithResponse(ctx, jobId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetAssetWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	assetId := request.GetString("assetId", "")

	resp, err := client.GetAssetWithResponse(ctx, assetId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetUrlAssetUploadJobWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	jobId := request.GetString("jobId", "")

	resp, err := client.GetUrlAssetUploadJobWithResponse(ctx, jobId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleUpdateAssetWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	assetId := request.GetString("assetId", "")
	var body target.UpdateAssetJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.UpdateAssetWithResponse(ctx, assetId, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleExchangeAccessTokenWithFormdataBodyWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.ExchangeAccessTokenFormdataRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.ExchangeAccessTokenWithFormdataBodyWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleIntrospectTokenWithFormdataBodyWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.IntrospectTokenFormdataRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.IntrospectTokenWithFormdataBodyWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleRevokeTokensWithFormdataBodyWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.RevokeTokensFormdataRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.RevokeTokensWithFormdataBodyWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetAppJwksWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	appId := request.GetString("appId", "")

	resp, err := client.GetAppJwksWithResponse(ctx, appId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetBrandTemplateDatasetWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	brandTemplateId := request.GetString("brandTemplateId", "")

	resp, err := client.GetBrandTemplateDatasetWithResponse(ctx, brandTemplateId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetBrandTemplateWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	brandTemplateId := request.GetString("brandTemplateId", "")

	resp, err := client.GetBrandTemplateWithResponse(ctx, brandTemplateId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleListBrandTemplatesWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	params := &target.ListBrandTemplatesParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["query"]; ok {
			params.Query = ptrVal(request.GetString("query", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["continuation"]; ok {
			params.Continuation = ptrVal(request.GetString("continuation", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["limit"]; ok {
			params.Limit = ptrVal(int32(request.GetInt("limit", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["ownership"]; ok {
			params.Ownership = ptrVal(target.OwnershipType(request.GetString("ownership", "")))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["sort_by"]; ok {
			params.SortBy = ptrVal(target.SortByType(request.GetString("sort_by", "")))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["dataset"]; ok {
			params.Dataset = ptrVal(target.DatasetFilter(request.GetString("dataset", "")))
		}
	}

	resp, err := client.ListBrandTemplatesWithResponse(ctx, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handlePublishBrandTemplateWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	var body target.PublishBrandTemplateJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.PublishBrandTemplateWithResponse(ctx, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignAnalyticsLinksWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	params := &target.GetDesignAnalyticsLinksParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["limit"]; ok {
			params.Limit = ptrVal(int32(request.GetInt("limit", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["continuation"]; ok {
			params.Continuation = ptrVal(request.GetString("continuation", ""))
		}
	}

	resp, err := client.GetDesignAnalyticsLinksWithResponse(ctx, designId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignAnalyticsPageViewsWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	var body target.GetDesignAnalyticsPageViewsJSONRequestBody
	if argData, ok := request.GetArguments()["body"]; ok {
		b, _ := json.Marshal(argData)
		json.Unmarshal(b, &body)
	}

	resp, err := client.GetDesignAnalyticsPageViewsWithResponse(ctx, designId, body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignAnalyticsViewersWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	params := &target.GetDesignAnalyticsViewersParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["link_id"]; ok {
			params.LinkId = ptrVal(request.GetString("link_id", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["first_viewed_after"]; ok {
			params.FirstViewedAfter = ptrVal(int64(request.GetInt("first_viewed_after", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["limit"]; ok {
			params.Limit = ptrVal(int32(request.GetInt("limit", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["continuation"]; ok {
			params.Continuation = ptrVal(request.GetString("continuation", ""))
		}
	}

	resp, err := client.GetDesignAnalyticsViewersWithResponse(ctx, designId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignAnalyticsViewsOverTimeWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")
	params := &target.GetDesignAnalyticsViewsOverTimeParams{}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["start_time"]; ok {
			params.StartTime = ptrVal(int64(request.GetInt("start_time", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["end_time"]; ok {
			params.EndTime = ptrVal(int64(request.GetInt("end_time", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["timezone"]; ok {
			params.Timezone = ptrVal(request.GetString("timezone", ""))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["limit"]; ok {
			params.Limit = ptrVal(int32(request.GetInt("limit", 0)))
		}
	}
	if args := request.GetArguments(); args != nil {
		if _, ok := args["continuation"]; ok {
			params.Continuation = ptrVal(request.GetString("continuation", ""))
		}
	}

	resp, err := client.GetDesignAnalyticsViewsOverTimeWithResponse(ctx, designId, params)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetDesignAnalyticsWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	designId := request.GetString("designId", "")

	resp, err := client.GetDesignAnalyticsWithResponse(ctx, designId)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetOidcJwksWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	resp, err := client.GetOidcJwksWithResponse(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleUserInfoWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	resp, err := client.UserInfoWithResponse(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetSigningPublicKeysWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	resp, err := client.GetSigningPublicKeysWithResponse(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetUserCapabilitiesWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	resp, err := client.GetUserCapabilitiesWithResponse(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleGetUserProfileWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	resp, err := client.GetUserProfileWithResponse(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}

func (h *Handler) handleUsersMeWithResponse(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	client, err := h.resolve(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	resp, err := client.UsersMeWithResponse(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}

	data, _ := json.MarshalIndent(resp, "", "  ")
	return mcp.NewToolResultText(string(data)), nil
}
